name: build site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install mkdocs-material
          pip install git+https://${{ secrets.MKDOCS_INSIDERS }}@github.com/squidfunk/mkdocs-material-insiders.git
      # Build the book
      - name: Build
        run: |
          mkdocs build
      # Push the site to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./site
          github_token: ${{ secrets.GITHUB_TOKEN }}